### ISSUE TITLE
温度传感器

### ISSUE THREAD

**Issue by 54tv** [bit3725/homeassistant-mi-air-quality-monitor#2]
你好，你这是提取空净的AQI作为一个单独的传感器，请问把温度提取出来应该类似吧，因为卧室没有其他温度传感器，想利用空净带的测室内温度，我没啥基础自己随便修改代码但是不成功，希望你有空的时候帮忙提取一个，谢谢

**Comment by bit3725** [comment]
这个 Component 读取的是 PM 2.5 检测仪的数据，没有温度相关的信息。
空气净化器 Homeassitant 已经有官方的 Component，包含温度湿度的数据。

**Comment by 54tv** [comment]
> 这个 Component 读取的是 PM 2.5 检测仪的数据，没有温度相关的信息。
> 空气净化器 Homeassitant 已经有官方的 Component，包含温度湿度的数据。
----------
好的谢谢，是我理解错了，我现在就用的官方组件，我以为温度也可以单独提取出来作为一个独立的传感器
